config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :articles
  resources :home
  devise_for :users
  root 'home#index'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'home/tag/:tag_name', to: 'home#index_by_tag', as: 'articles_by_tag'

  get 'home/show/:id', to: 'home#show', as: 'home_article'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  validates_presence_of :title, presence: true
  validates_presence_of :content, presence: true

  belongs_to :tag, optional: true
  attr_accessor :tag_name
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :articles

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :authenticate_user!
  before_action :check_admin

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show; end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit; end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        update_tag
        format.html { redirect_to article_url(@article), notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        update_tag
        format.html { redirect_to article_url(@article), notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy!

    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
    @article.tag_name = @article.tag&.name
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :content, :tag_name)
  end

  def update_tag
    tag_name = params[:article][:tag_name]
    return if tag_name.blank?

    tag = Tag.find_or_create_by(name: tag_name.strip)
    @article.update(tag:)
  end

  def check_admin
    if current_user.admin?
      return if request.path.start_with?(articles_path)

      redirect_to root_path, alert: 'Access Denied'
    else
      redirect_to cancel_user_registration_path, alert: 'Access Denied'
    end
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :set_tags, only: %i[index index_by_tag show]
  def index
    @articles = Article.all
  end

  def index_by_tag
    @tag = Tag.find_by(name: params[:tag_name])
    @articles = if @tag
                  @tag.articles
                else
                  []
                end
  end

  # GET /articles/1 or /articles/1.json
  def show
    @article = Article.find(params[:id])
    @article.tag.name = @article.tag&.name
  end

  private

  def set_tags
    @tags = Tag.all
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id @article %>" >
  <div class="text-center">
    <h2 class="text-2xl font-bold text-gray-800"><%= @article.title %></h2>
    <p class="text-gray-500 mt-2 pb-10"><%= @article.created_at.strftime("%B %d, %Y") %> | <%= article.tag.name %></p>
  </div>
  <p class="mt-4 text-gray-700 whitespace-pre-wrap"><%= @article.content %></p>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-4">
    <%= form.label :title, class: "block text-gray-700 font-bold mb-2" %>
    <%= form.text_field :title, class: "shadow appearance-none border rounded w-full py-2 px-3 bg-gray-200 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-4">
    <%= form.label :tag, class: "block text-gray-700 font-bold mb-2" %>
    <%= form.text_field :tag_name, class: "shadow appearance-none border rounded w-full py-2 px-3 bg-gray-200 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-6">
    <%= form.label :content, class: "block text-gray-700 font-bold mb-2" %>
    <%= form.text_area :content, rows: 30, class: "shadow appearance-none border rounded w-full py-2 px-3 bg-gray-200 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="flex items-center justify-between">
    <%= form.submit "Create Article", class: "bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<!-- Navbar -->
<nav class="w-full bg-indigo-600 fixed top-0 left-0 z-70">
  <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 flex items-center justify-between h-24">
    <div class="flex-shrink-0">
      <%= link_to 'Redator Dev', home_index_path, class: "text-white text-2xl font-bold" %>
    </div>
    <div class="flex items-center">
      <%= link_to 'New Article', new_article_path, class: "text-white text-sm font-medium hover:text-gray-300 mr-4" %>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-white text-sm font-medium hover:text-gray-300" %>
    </div>
  </div>
</nav>

<!-- Content -->
<div class="flex flex-col items-center min-h-screen py-24 px-4 bg-gray-100 mt-16">
  <!-- Notification Message -->
  <% if notice %>
    <p class="text-green-600 bg-green-100 border border-green-200 rounded-lg p-4 mb-4">
      <%= notice %>
    </p>
  <% end %>

  <div class="w-full max-w-4xl text-center">
    <h1 class="text-2xl font-bold mb-6">Editing Article</h1>

    <%= form_with(model: @article, local: true) do |form| %>
      <div class="bg-white p-6 rounded-lg shadow-md">
        <div class="mb-4">
          <%= form.label :title, class: "block text-left mb-2 text-gray-700" %>
          <%= form.text_field :title, class: "w-full px-4 py-2 border rounded-lg bg-gray-200", placeholder: "Enter article title" %>
        </div>

        <div class="mb-4">
          
          <div id="tag-creation" class="mt-2">
            <%= form.label :tag, class: "block text-left mb-2 text-gray-700" %>
            <%= form.text_field :tag_name, class: "w-full px-4 py-2 border rounded-lg bg-gray-200" %>
          </div>
        </div>

        <div class="mb-4">
          <%= form.label :content, class: "block text-left mb-2 text-gray-700" %>
          <%= form.text_area :content, class: "w-full px-4 py-2 border rounded-lg bg-gray-200", rows: 10, placeholder: "Enter article content" %>
        </div>

        <div class="mb-4">
          <%= form.submit "Update Article", class: "px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700" %>
        </div>
      </div>
    <% end %>

    <br>

    <div>
      <%= link_to "Show this article", @article, class: "text-indigo-600 hover:underline" %> |
      <%= link_to "Back to articles", articles_path, class: "text-indigo-600 hover:underline" %>
    </div>
  </div>
</div>

app/views/articles/home.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article %>
    </p>
  <% end %>
</div>

app/views/articles/homeshow.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<!-- Barra de Navegação -->
<nav class="w-full bg-indigo-600 fixed top-0 left-0 z-70">
  <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 flex items-center justify-between h-24">
    <!-- Nome da Aplicação -->
    <div class="flex-shrink-0">
      <%= link_to 'Redator Dev', home_index_path, class: "text-white text-2xl font-bold" %>
    </div>
    <!-- Links de Navegação -->
    <div class="flex items-center">
      <%= link_to 'New Article', new_article_path, class: "text-white text-sm font-medium hover:text-gray-300 mr-4" %>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-white text-sm font-medium hover:text-gray-300" %>
    </div>
  </div>
</nav>

<!-- Conteúdo da Página -->
<div class="flex flex-col items-center min-h-screen py-24 px-4 bg-gray-100 mt-16">
  <!-- Mensagem de Notificação -->
  <% if notice %>
    <p class="text-green-600 bg-green-100 border border-green-200 rounded-lg p-4 mb-4">
      <%= notice %>
    </p>
  <% end %>

  <div class="w-full max-w-4xl text-center">

    <div id="articles" class="mt-8 grid grid-cols-1 gap-6 lg:grid-cols-1  w-11/12 place-items-center mx-auto">
      <% @articles.each do |article| %>
        <div class="bg-white overflow-hidden shadow rounded-lg p-6 w-full mx-auto">
          <%= link_to article_path(article) do %>
            <div id="<%= dom_id article %>" class="text-center">
              <div class="flex items-center justify-center">
                <h2 class="text-xl font-semibold text-gray-800">
                  <%= article.title %>
                </h2>
              </div>

              <p class="text-gray-500 mt-2">
                <%= article.created_at.strftime("%B %d, %Y") %> | <%= article.tag&.name %>
              </p>
            </div> 
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<!-- Barra de Navegação -->
<nav class="w-full bg-indigo-600 fixed top-0 left-0 z-70">
  <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 flex items-center justify-between h-24">
    <!-- Nome da Aplicação -->
    <div class="flex-shrink-0">
      <%= link_to 'Redator Dev', home_index_path, class: "text-white text-2xl font-bold" %>
    </div>
    <!-- Links de Navegação -->
    <div class="flex items-center">
      <%= link_to 'New Article', new_article_path, class: "text-white text-sm font-medium hover:text-gray-300 mr-4" %>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-white text-sm font-medium hover:text-gray-300" %>
    </div>
  </div>
</nav>

<!-- Conteúdo da Página -->
<div class="flex flex-col items-center min-h-screen py-24 px-4 bg-gray-100 mt-16">
  <div class="w-full max-w-4xl bg-white shadow rounded-lg p-8">
    <h1 class="text-3xl font-bold text-gray-800 mb-6">New Article</h1>

    <%= render "form", article: @article %>

    <div class="mt-6">
      <%= link_to "Back to articles", articles_path, class: "text-gray-500 hover:text-gray-700" %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<!-- Barra de Navegação -->
<nav class="w-full bg-indigo-600 fixed top-0 left-0 z-70">
  <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 flex items-center justify-between h-24">
    <!-- Nome da Aplicação -->
    <div class="flex-shrink-0">
      <%= link_to 'Redator Dev', home_index_path, class: "text-white text-2xl font-bold" %>
    </div>
    <!-- Links de Navegação -->
    <div class="flex items-center">
      <%= link_to 'New Article', new_article_path, class: "text-white text-sm font-medium hover:text-gray-300 mr-4" %>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-white text-sm font-medium hover:text-gray-300" %>
    </div>
  </div>
</nav>

<!-- Conteúdo da Página -->
<div class="flex flex-col items-center min-h-screen py-24 px-4 bg-gray-100 mt-16">
  <!-- Mensagem de Notificação -->
  <% if notice %>
    <p class="text-green-600 bg-green-100 border border-green-200 rounded-lg p-4 mb-4">
      <%= notice %>
    </p>
  <% end %>

  <div class="w-full max-w-4xl bg-white shadow rounded-lg p-8">
    <%= render @article %>

    <div class="flex justify-between mt-6">
      <%= link_to "Edit this article", edit_article_path(@article), class: "bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600" %>
      <%= link_to "Back to articles", articles_path, class: "text-gray-500 hover:text-gray-700" %>
      <%= button_to "Destroy this article", @article, method: :delete, data: { confirm: "Are you sure?" }, class: "bg-red-500 text-white py-2 px-4 rounded hover:bg-red-600" %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="flex flex-col items-center justify-center min-h-screen py-8">
  <nav class="w-full bg-indigo-600 fixed top-0 left-0 z-70" >
    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 flex items-center justify-between h-24">
      <!-- Nome da Aplicação -->
      <div class="flex-shrink-0">
        <%= link_to 'Redator Dev', root_path, class: "text-white text-2xl font-bold" %>
      </div>
      <!-- Menu de Pesquisa por Tags -->
      <div class="relative" data-controller="dropdown">
        <button class="text-white focus:outline-none">
          Search by Tags
        </button>
        <div data-dropdown-target="menu" class="hidden absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg py-1 z-20">
          <!-- Lista de tags -->
          <% @tags&.each do |tag| %>
            <%= link_to tag.name, articles_by_tag_path(tag.name), class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" %>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
  
  <div class="w-full max-w-4xl text-center">

    <div id="articles" class="mt-8 grid grid-cols-1 gap-6 lg:grid-cols-1  w-11/12 place-items-center mx-auto">
      <% @articles.each do |article| %>
        <div class="bg-white overflow-hidden shadow rounded-lg p-6 w-full mx-auto">
          <div id="<%= dom_id article %>" class="text-center">
            <%= link_to home_article_path(article) do %>
                <div class="flex items-center justify-center">
                  <h2 class="text-xl font-semibold text-gray-800">
                    <%= article.title %>
                  </h2>
                </div>
            <% end %>

            <p class="text-gray-500 mt-2">
              <%= article.created_at.strftime("%B %d, %Y") %> | <%= link_to article.tag&.name, articles_by_tag_path(article.tag&.name), class: "text-indigo-600"%>
            </p>
          </div> 
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/index_by_tag.html.erb
<div class="flex flex-col items-center justify-center min-h-screen py-8">
  <nav class="w-full bg-indigo-600 fixed top-0 left-0 z-70" >
    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 flex items-center justify-between h-24">
      <!-- Nome da Aplicação -->
      <div class="flex-shrink-0">
        <%= link_to 'Redator Dev', root_path, class: "text-white text-2xl font-bold" %>
      </div>
      <!-- Menu de Pesquisa por Tags -->
      <div class="relative" data-controller="dropdown">
        <button class="text-white focus:outline-none" >
          Search by Tags
        </button>
        <div data-dropdown-target="menu" class="hidden absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg py-1 z-20">
          <!-- Lista de tags -->
          <% @tags&.each do |tag| %>
            <%= link_to tag.name, articles_by_tag_path(tag.name), class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" %>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
  
  <div class="w-full max-w-4xl text-center">

    <div id="articles" class="mt-8 grid grid-cols-1 gap-6 lg:grid-cols-1  w-11/12 place-items-center mx-auto">
      <% @articles.each do |article| %>
        <div class="bg-white overflow-hidden shadow rounded-lg p-6 w-full mx-auto">
          <%= link_to home_article_path(article) do %>
            <div id="<%= dom_id article %>" class="text-center">
              <div class="flex items-center justify-center">
                <h2 class="text-xl font-semibold text-gray-800">
                  <%= article.title %>
                </h2>
              </div>

              <p class="mt-2">
                <span class="text-gray-500"><%= article.created_at.strftime("%B %d, %Y") %></span> | 
               <span class="text-indigo-600"><%= article.tag&.name %></span>
              </p>
            </div> 
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/show.html.erb
  <!-- Barra de Navegação -->
  <nav class="w-full bg-indigo-600 fixed top-0 left-0 z-70" data-controller="dropdown">
    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 flex items-center justify-between h-24">
      <!-- Nome da Aplicação -->
      <div class="flex-shrink-0">
        <%= link_to 'Redator Dev', root_path, class: "text-white text-2xl font-bold" %>
      </div>
      <!-- Menu de Pesquisa por Tags -->
      <div class="relative" data-controller="dropdown">
        <button class="text-white focus:outline-none">
          Search by Tags
        </button>
        <div data-dropdown-target="menu" class="hidden absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg py-1 z-20">
          <!-- Lista de tags -->
          <% @tags&.each do |tag| %>
            <%= link_to tag.name, articles_by_tag_path(tag.name), class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" %>
          <% end %>
        </div>
      </div>
    </div>
  </nav>

  <!-- Conteúdo da Página -->
  <div class="flex flex-col items-center min-h-screen py-24 px-4 bg-gray-100 mt-16">
    <!-- Mensagem de Notificação -->
    <% if notice %>
      <p class="text-green-600 bg-green-100 border border-green-200 rounded-lg p-4 mb-4">
        <%= notice %>
      </p>
    <% end %>

    <!-- Artigo -->
    <div class="bg-white shadow-md rounded-lg p-6 w-full max-w-4xl mb-6">
      <div id="<%= dom_id @article %>">
        <div class="text-center">
          <h2 class="text-2xl font-bold text-gray-800"><%= @article.title %></h2>
          <p class="text-gray-500 mt-2 pb-10"><%= @article.created_at.strftime("%B %d, %Y") %> | <%= link_to @article.tag.name, articles_by_tag_path(@article.tag.name), class: "text-indigo-600" %> </p>
        </div>
        <p class="mt-4 text-gray-700 whitespace-pre-wrap text-start"><%= @article.content %></p>
      </div>
    </div>

    <!-- Link de Voltar -->
    <div class="mt-4">
      <%= link_to "Back to articles", home_index_path, class: "text-indigo-600 hover:text-indigo-900 font-semibold" %>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Redator DEV</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="shortcut icon" href="<%= asset_path('logo.svg') %>" type="image/x-icon">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-100">
    <%= yield %>
  </body>
</html>